FROM inspircd/inspircd-docker:latest

# Setup IRC
USER inspircd
ENV INSP_NET_SUFFIX .deadpackets.pw
ENV INSP_NET_NAME VladimirUnderground
ENV INSP_ADMIN_NAME Vladimir
ENV INSP_ADMIN_NICK vlad1m1r
ENV INSP_ADMIN_EMAIL vladimir@deadpackets.pw